### ISSUE TITLE
Small screens can't display the Recent models list on KIE Sandbox's home page

### ISSUE THREAD

**Issue by porcelli** [IBM/bamoe-issues#186]
The video shows that I can't scroll to the list of assets, fortunately I was able to expand a little the browser and was able to scroll a bit to access.

https://user-images.githubusercontent.com/119395/254289538-319a2d1e-e283-4827-bf80-37ee694f4ce1.mov

**Comment by tiagobento** [comment]
Moving this to `kiegroup/kie-issues`. See https://github.com/kiegroup/kie-issues/issues/484
