### ISSUE TITLE
UI stuck on loading when importing a specific repo on KIE Sandbox

### ISSUE THREAD

**Issue by porcelli** [IBM/bamoe-issues#188]
around 50% of the times when trying to clone this [1] repository, the UI get in loading state forever.

[1] - https://github.com/snandakumarops/transaction-monitoring-dmn-kogito

https://user-images.githubusercontent.com/119395/254299937-0f520ee2-0043-4364-bbc5-9a4d58cb4af3.mov

**Comment by tiagobento** [comment]
Moved to `kiegroup/kie-issues`. See https://github.com/kiegroup/kie-issues/issues/483
