### ISSUE TITLE
DMN file not loading

### ISSUE THREAD

**Issue by porcelli** [IBM/bamoe-issues#189]
Using this repository [1], there's an DMN file (TransactionMonitoringDMN) that fails to load and having the loading spinning forever.

[1] - https://github.com/snandakumarops/transaction-monitoring-dmn-kogito

https://user-images.githubusercontent.com/119395/254305424-59f41ce8-21bc-406a-a13d-4d4f78949ebb.mov

### Workaround 01
Please notice the git repository contains the same models twice. We can see it as:
- https://github.com/snandakumarops/transaction-monitoring-dmn-kogito/tree/master/src/main/resources
- https://github.com/snandakumarops/transaction-monitoring-dmn-kogito/tree/master/target/classes

In these folders we will find out **AmlDecisions**, **staticFraudRules** and **TransactionMonitoringDMN** are duplicated.

The issue #189 **is not reproducible** once we delete the duplicates from https://github.com/snandakumarops/transaction-monitoring-dmn-kogito/tree/master/target/classes

### Workaround 02
Using VSCode DMN Extension can be the **TransactionMonitoringDMN** model opened without any issue.

**Comment by jomarko** [comment]
May be related to work with included models. Did you recheck opening of that file once you manually remove the `import` xml tag?

**Comment by jomarko** [comment]
The issue really seems to be related to imports:
![image](https://github.com/IBM/bamoe-issues/assets/8044780/a7629eea-0d6c-4483-b08a-00da93237b9f)

**Comment by porcelli** [comment]
@tiagobento maybe include this use case as part of the new dmn editor infra?

**Comment by jomarko** [comment]
https://github.com/IBM/bamoe-issues/issues/189#issuecomment-1673090315 @porcelli what does it mean please. Could you please clarify more?

**Comment by porcelli** [comment]
@jomarko basically address this issue as part of the new editor effort that @tiagobento is working on. not sure if it's worth invest to fix the current one

**Comment by jomarko** [comment]
_new effort_ is that something specific? I know we work on removing GWT for example, but I am not aware of any other efforts regarding DMN Editor. If you, could we please share it with whole team?

**Comment by jomarko** [comment]
This issue is probably resolved with 9.1.0 rc1 build.

![Screenshot 2024-05-29 155107](https://github.com/IBM/bamoe-issues/assets/8044780/a1c4fe69-845f-46b2-9a0a-f0caf0a6b933)

**Comment by jomarko** [comment]
Yes, using `BAMOE 9.1.0-ibm-0001` and the New DMN Editor, the file can be opened.
