### ISSUE TITLE
Add support for Gradle build system

### ISSUE THREAD

**Issue by porcelli** [IBM/bamoe-issues#191]
As a user I want use Gradle as build system for Quarkus or SpringBoot.

As a user I expect to have an accelerator for Gradle.

**Comment by tiagobento** [comment]
What version of SpringBoot?

**Comment by porcelli** [comment]
SpringBoot v3 and Quarkus v3 :)

**Comment by kmacedovarela** [comment]
Can you shade some light on the intended scope of this git issue target?
If we are talking about v3 runtimes (mentioned by @porcelli), we are not considering the full extent of deps used within the different engines available within kie projects correct? 
In other words, it covers a **subset of supported deps** used with Gradle, available **only for kogito-enabled projects** - not kie-server projects. Is this understanding correct?

**Comment by baldimir** [comment]
The scope of this may include creating a Gradle plugin for Kogito, then having the set of kogito-examples we currently have, copied and updated to build with Gradle + fixing things along that don't work + adding support for such projects to Sandbox (not sure about this last part though).

**Comment by porcelli** [comment]
@kmacedovarela this issue is scoped for the Kogito based stream, so Drools 8+ and Kogito.
