### ISSUE TITLE
Rebuild 9.0.0 images with new base image version

### ISSUE THREAD

**Issue by baldimir** [IBM/bamoe-issues#194]
There is a new version of the base image for the KIE Sandbox images. This new version of base image fixes some CVES. We need to rebuild BAMOE images to get those CVE fixes.

**Comment by baldimir** [comment]
Based on https://github.com/IBM/bamoe-issues/issues/193, it is enough to just rebuild the images, as the base image in the same version was updated. So starting the build.

**Comment by eduardocerqueira** [comment]
Thank you! closing this issue

**Comment by baldimir** [comment]
We don't know how soon the base images will be fixed, so closing this. There will be a new issue for another rebuild when the fixes are ready.
