### ISSUE TITLE
Prepare updated container images for upload to Fix Central

### ISSUE THREAD

**Issue by martinweiler** [IBM/bamoe-issues#195]
This task follows up on https://github.com/IBM/bamoe-issues/issues/194 with additional requirements to make the artifacts ready to be uploaded to Fix Central:

- Renaming: Use fourth number to indicate this release is a Fixpack to address CVEs, eg: `bamoe-9.0.0.IF001-<IMAGE_NAME>.tar.gz` (where IF stands for Interim Fix)
- Readme: there should be a readme with some basic details, ie. contents of the fix, what it is fixing, and how to apply, and revert if that's possible... or simply pointing to some existing fix application instructions from the readme should be sufficient too

**Comment by YajieY** [comment]
@martinweiler @eduardocerqueira I'd double check this is what we want: 
Renaming: Use fourth number to indicate this release is a Fixpack to address CVEs, eg: bamoe-9.0.0.IF001-<IMAGE_NAME>.tar.gz (where IF stands for Interim Fix)
<== this is a versioning convention for VRMF (IBM 99% products, and DBA products use the fourth digit for interim fixes (a concious decision no longer to release a full fix pack due to monthly cadence). 

However, we claimed BAMOE follows semantic versioning principal (effectively VMF), so is it more of bamoe-9.0.IF001 ? Or we treat this as an one-off CVE patch to roll up to 9.0.1 cumulatively? Thanks. 
BAMOE 9.0 Support Policy:[ https://www.ibm.com/support/pages/node/7007883](https://www.ibm.com/support/pages/node/7007883)

**Comment by martinweiler** [comment]
Thanks for your input @YajieY - we are using `bamoe-9.0.IF001-<IMAGE_NAME>.tar.gz` now.

**Comment by martinweiler** [comment]
Readme file (draft):

```
Status:                    Fix

Product:                   IBM Business Automation Open Editions

Release:                   9.0.0

Operating System:          All operating systems

Date:                      2023-08-10

Abstract:                  This interim fix includes fixes for these libraries to address: 
                           RHSA-2023:4347, RHSA-2023:4349, RHSA-2023:4354, RHSA-2023:4569

Interim fix installation instructions
=====================================

Refer to the BAMOE Canvas installation guide:
https://ibmdocs-test.dcs.ibm.com/docs/en/ibamoe/9.0.0?topic=installation-bamoe-canvas


BAMOE Canvas Images - Interim Fix details
=========================================

File: IBM Business Automation Manager Open Editions 9.0.IF001 – BAMOE Canvas Image
- File Name:         bamoe-9.0.IF001-canvas-image.tar.gz
- File Size (bytes): 112950760
- SHA:               ecbf3689163630041a2cd62e161be2d0a5185227
- Description:       BAMOE Canvas is a web application that provides authoring tools for Decisions and Workflows, directly in the browser.

Fixed issues in BAMOE Canvas Image:
- RHSA-2023:4349: libxml2 security update
- RHSA-2023:4347: libeconf security update
- RHSA-2023:4569: dbus security update
- RHSA-2023:4354: curl security update

File: IBM Business Automation Manager Open Editions 9.0.IF001 – BAMOE Canvas Extended Services Image
- File Name:         bamoe-9.0.IF001-extended-services-image.tar.gz
- File Size (bytes): 68701840
- SHA:               d0baaf9dee61b4694d64720d6d7baf19f92aff98
- Description:       This image provides features like DMN Runner, static validation of DMN, BPMN models, and also provides a proxy to communicate with OpenShift and Kubernetes clusters.
 
Fixed issues in BAMOE Canvas Extended Services Image:
- RHSA-2023:4349: libxml2 security update
- RHSA-2023:4354: curl security update

File: IBM Business Automation Manager Open Editions 9.0.IF001 – BAMOE Canvas Git CORS Proxy Image
- File Name:         bamoe-9.0.IF001-git-cors-proxy-image.tar.gz
- File Size (bytes): 137046009
- SHA:               07321eb2a757ca7ca06b23d2cf2c825cb0784139
- Description:       This image provides a proxy to allow BAMOE Canvas web app to communicate with Git providers, like github.com and bitbucket.org.

Fixed issues in BAMOE Canvas Git CORS Proxy Image:
- RHSA-2023:4349: libxml2 security update
- RHSA-2023:4354: curl security update
```

**Comment by martinweiler** [comment]
Renamed the files and added the readme file to the image-updates folder

**Comment by YajieY** [comment]
Hi @martinweiler the install guide link in the readme is our internal testing doc env, please replace it with the public one: https://www.ibm.com/docs/en/ibamoe/9.0.0?topic=installation-bamoe-canvas
Thanks!

Refer to the BAMOE Canvas installation guide:
https://ibmdocs-test.dcs.ibm.com/docs/en/ibamoe/9.0.0?topic=installation-bamoe-canvas

**Comment by martinweiler** [comment]
Good catch @YajieY
