### ISSUE TITLE
Change BAMOE documentation with screenshots and new material about the new React-based DMN Editor.

### ISSUE THREAD

**Issue by tiagobento** [IBM/bamoe-issues#197]

**Comment by jomarko** [comment]
Is this ticket about https://github.com/IBM/bamoe-docs ?

**Comment by tiagobento** [comment]
@jomarko Yes.

**Comment by jomarko** [comment]
I tend to think this ticket is outdated now? I mean we are probably done with new DMN Editor documentation?
