### ISSUE TITLE
Docker Compose Page is missing information.

### ISSUE THREAD

**Issue by Josephblt** [IBM/bamoe-issues#198]
The issues are all related to this Doc page:
https://www.ibm.com/docs/en/ibamoe/9.0.0?topic=canvas-docker-compose

The build step in the Docker Compose is missing requirements. It won't work unless KIE-Tools is fully built at least once. So we should either remove it entirely or add those requirements. 

The Run part works but it is necessary to clone the repository. We should add those requirements as well. I think it would be a better idea to have the Run part before the Build steps. 

There is no information about Docker, we should at least mention it and point to their install pages.

**Comment by thiagoelg** [comment]
The `kie-tools/kie-sandbox-distribution` docker-compose.yml and the BAMOE product docker-compose.yml files are different, and the documentation should describe how to use the BAMOE version.

For BAMOE there's no need to clone and build the repository, the user only needs Docker installed and run `docker compose up`, and this is what the documentation should state.

**Comment by tiagobento** [comment]
We also need to add to the documentation where customers can get access to the BAMOE Canvas docker-compose.yml files.

**Comment by Josephblt** [comment]
Issue moved. Closing it.
