### ISSUE TITLE
GitHub new "Fine-grained personal access tokens" doesn't work with KIE Sandbox

### ISSUE THREAD

**Issue by porcelli** [IBM/bamoe-issues#22]
There's a new GitHub token type called "Fine-grained personal access tokens" that KIE Sandbox is not compatible with. 

ps: this feature is still in beta, so maybe we should only do a better communication of this not being supported.

**Comment by kbowers-ibm** [comment]
Underneath the textbox where the github token is entered, we have a note saying "Your token must include the 'repo' and 'gist' scopes." If better communication is needed while it's still in beta, we could potentially just add to the note there and specify that "Fine-grained personal access tokens are currently not supported."

**Comment by porcelli** [comment]
@kbowers-ibm this is fine for now, but as we plan to continue to support GitHub we need to keep up to date with their new updates.

Of course, this is not a priority for now (well, until it stops working); but it needs to be on our radar.

**Comment by tiagobento** [comment]
@porcelli Shouldn't this be on [kiegroup/kie-issues](https://github.com/kiegroup/kie-issues)?

**Comment by porcelli** [comment]
@tiagobento sure, but as there is no easy move ticket between orgs... maybe leave it here? :)

**Comment by tiagobento** [comment]
Moving this to `kiegroup/kie-issues` so we can track it as part of:
- https://github.com/kiegroup/kie-issues/issues/487
