### ISSUE TITLE
before and after TaskAssignmentsAddedEvent show same user details in both events

### ISSUE THREAD

**Issue by cimbalek** [IBM/bamoe-issues#39]
Tracking purposes:
https://issues.redhat.com/browse/RHPAM-4442

**Comment by cimbalek** [comment]
PRs to main:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/634
https://github.com/kiegroup/jbpm/pull/2280

**Comment by martinweiler** [comment]
Closing, this is now tracked in https://github.com/bamoe/private-bamoe-issues/issues/212
