### ISSUE TITLE
beforeTaskCompletedEvent shows updated value of process variables

### ISSUE THREAD

**Issue by cimbalek** [IBM/bamoe-issues#40]
For purpose of tracking https://issues.redhat.com/browse/RHPAM-4446

**Comment by cimbalek** [comment]
https://github.com/kiegroup/droolsjbpm-knowledge/pull/639
https://github.com/kiegroup/jbpm/pull/2284

Customer needs should be satisfied by additional info provided via TaskContext

**Comment by martinweiler** [comment]
Closing, this is now tracked in https://github.com/bamoe/private-bamoe-issues/issues/212
